### ISSUE TITLE
Create the sensor toggle drawer

### ISSUE THREAD

**Issue by Julielsu** [simeeid/TDT4290Group1#7]
Create this drawer in the web:
![image](https://github.com/simeeid/TDT4290Group1/assets/144443907/f16f04d5-33b8-4513-bbd8-7145b865ef8d)

- [ ] The drawer should be able to open and close
- [ ] The different sensors should be able to have both status of chosen and unchosen

Tips:
- Drawer, list of sensors (and maybe status button and close/open button) should be independent components
- Simple components created as atoms, combined components created as molecules

Tips2:
- May be smart to utilize a library of components such as Chakra-ui (@chakra-ui/react)

Definition of done: The drawer matches the design provided in the image and the functionality described in the issue

**Comment by OliviaWork** [comment]
Completed in #26, issue superseded by #18 in accordance with the new design.
