### ISSUE TITLE
Cryptography

### ISSUE THREAD

**Issue by Julielsu** [simeeid/TDT4290Group1#84]
!! Should be completed after #81 and #82 

- [ ] encrypt user passwords (reccomend SHA256)
- [ ] Consider adding salt and pepper to passwords
- [ ] Consider if any other user information should be encrypted. Location? Other sensor data?

Definition of done: all passwords are encrypted and other data you feel necessary

**Comment by OliviaWork** [comment]
Alternative to plain SHA256 for later discussion: https://en.wikipedia.org/wiki/PBKDF2
